config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get '/', to: 'tops#index'
  get 'about', to: 'tops#about'
  resources :accounts, only: %i[show edit update] do
    collection do
      get 'withdrawal'
    end

    member do
      get 'release'
    end
  end

  resources :recipes, only: %i[index new create show edit update destroy] do
    resource :favorite, only: %i[create destroy]

    member do
      get 'release'
    end

    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  mount_uploader :food, FoodUploader

  VALID_PASSWORD_REGEX = /\A[ぁ-んァ-ン一-龥]+\z/.freeze
  with_options presence: true do
    validates :recipe_name, length: { in: 1..20 }
    validates :main_food, format: { with: VALID_PASSWORD_REGEX, flash: { info: 'は半角英数を両方含む必要があります' } }
    validates :time
    validates :price
  end

  def self.search(search)
    if search == ""
      redirect_to serach_recipes_path
    else
      Recipe.where(['recipe_name LIKE(?) OR main_food LIKE(?)', "%#{search}%", "%#{search}%"]).order('created_at DESC')
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = Recipe.all.page(params[:page]).order(created_at: :desc).per(5).includes(:user, :favorites)
  end

  def show
    @user = current_user
    @recipe = Recipe.find(params[:id])
  end

  def new
    @user = current_user
    @recipe = Recipe.new
    @private = Recipe.order(created_at: :desc).first
  end

  def edit
    @user = current_user
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      @recipe = Recipe.new(recipe_params)
      flash.now[:info] = '入力ミスがあります'
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_update)
      redirect_to recipe_path(@recipe.id)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to account_path(current_user), flash: { info: "レシピを削除しました。" }
  end

  def release
    @user = current_user
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:recipe_name, :main_food, :food, :recipe_how, :material, :price, :time, :user_id)
  end

  def recipe_update
    params.require(:recipe).permit(:recipe_name, :main_food, :food, :recipe_how, :material, :price, :time)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def placeholder_method
    <<~"EOS"
      例：
      1.ニラを3cmずつにきります。
      2.ニラを切った後にんにくのすりおろしを炒めます。
    EOS
  end

  def placeholder_material
    <<~"EOS"
      例：
      1.豚肉     200グラム
      2.ニラ     一袋の半分
      3.しょうゆ  大さじ1.5
    EOS
  end
end

app/views/recipes/edit.html.erb
<% provide(:title, 'レシピ編集')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <%= render 'shared/in_sidebar'%>
  <div class="content-wrapper">
    <div class="page-title">
      <h1 class="recipe-title-font gray-color">レシピ編集</h1>
    </div>
    <div class="recipe-wrapper">
      <div class="recipe-container">
        <%= form_with model: @recipe, local: true do |f| %>
          <div class="recipe-box">
            <div class="recipe-label1">
              <label class="recipe-label gray-color" for="recipe_name">レシピの名前</label>
            </div>
            <div class="recipe-form">
              <%= f.text_field :recipe_name, placeholder: "例：ニラと豚肉のスタミナ丼", class: "recipe-form-ctrl form-space" %>
            </div>
            <div class="main-food-box">
              <p class="main-food-col">※メインの材料</p>
              <%= f.text_field :main_food, placeholder: "例：豚肉", class:"main-food" %>
            </div>
          </div>
          <div class="recipe-col-3">
            <%= f.label :food, id: "food", class: "fa-2x recipe-label gray-color fa-solid fa-camera center" do %>
              <div class="recipe-label3">
                <p>料理の写真</p>
              </div>
              <div class="recipe-form">
                <%= f.file_field :food %>
              </div>
            <% end %>
            <div class="recipe-number-wrapper">
              <div class="recipe-number-wrapper-col">
                <%= f.label :調理時間, class: "recipe-label gray-color recipe-people"%>
              </div>
              <div class="field-wrapper flex">
                <%= f.number_field :time, min: 1, class: "recipe-form-ctrl2 gray-color" %>
                <div class="font-people">分</div>
              </div>
              <div class="recipe-number-wrapper-col">
                <%= f.label :値段, class: "recipe-label gray-color recipe-price"%>
              </div>
              <div class="field-wrapper flex">
                <%= f.number_field :price, min: 1, class: "recipe-form-ctrl2 gray-color" %>
                <div class="font-price">円</div>
              </div>
            </div>
          </div>
          <div class="recipe-sentence-box">
            <nav class="recipe-introduction">
              <div class="recipe-label2">
                <label class="recipe-label gray-color" for="recipe_introduction">作り方</label>
              </div>
              <div class="recipe-form">
                <%= f.text_area :recipe_how, placeholder: placeholder_method,rows: 4, class: "recipe-intro-form-ctrl form-space" %>
              </div>
            </nav>
            <nav class="recipe-trick">
              <div class="recipe-label2">
                <%= f.label :材料・分量, class: "recipe-label gray-color" %>
              </div>
              <div class="recipe-form">
                <%= f.text_area :material, placeholder: placeholder_material,rows: 4, class: "recipe-intro-form-ctrl form-space" %>
              </div>
            </nav>
          </div>
          <div class="submit center">
            <%= f.submit "更新", class: "create-recipe-submit" %>
          </div>
          <div class="destroy-submit center">
            <%= link_to 'レシピ削除', recipe_path,class: "destroy-recipe-btn", data: {confirm: "レシピを削除しますか？"}, method: :delete %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<% provide(:title, 'レシピ新着一覧')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <% if user_signed_in? %>
    <%= render 'shared/in_sidebar'%>
  <% else %>
    <%= render 'shared/out_sidebar'%>
  <% end %>
  <div class="preview-page-wrapper">
    <div class="order-title-wrap">
      <h2 class="order-title gray-color center">新着順</h2>
      <p class="order-title-comment center">最近投稿されたレシピを試してみよう！</p>
    </div>
    <div class="search-wrap center">
      <%= form_with(url: search_recipes_path, local: true, method: :get ) do |f| %>
        <%= f.search_field :keyword, class: 'recipe-name-search', placeholder: 'キーワードで検索' %>
        <%= f.submit '検索', class: "submit-search"%>
      <% end %>
    </div>
    <% @recipes.each do |recipe| %>
      <div class="recipe-preview">
        <% if recipe.food? %>
          <%= link_to release_recipe_path(recipe.id) do %>
            <%= image_tag recipe.food.url, alt: "レシピ写真", class: "food-preview-img" %>
          <% end %>
        <% else %>
          <%= link_to release_recipe_path(recipe.id), class: "preview-name-path" do %>
            <div class="not-food-img-box">
              <div class="not-food-img-posi">
                <div>
                  <i class="not-food-img fa-solid fa-utensils"></i>
                </div>
                <div class="not-found">
                  <p>not-image</p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="recipe-preview-wrapp">
          <div class="preview-name">
            <%= link_to release_recipe_path(recipe.id), class: "preview-name-path" do %>
              <%= recipe.recipe_name %>
            <% end %>
            <div class="list-favorite" id="favorite_recipe_<%= recipe.id %>">
              <i class="fas fa-thumbs-up"></i>
              <%= recipe.favorites.size %>
            </div>
          </div>
          <div class="preview-item-wrap">
            <div class="preview-price-title">
              <p>調理の費用</p>
            </div>
            <div class="preview-price right">
              <%= recipe.price%>円
            </div>
          </div>
          <div class="preview-item-wrap">
            <div class="preview-time-title">
              <p>調理にかかる時間</p>
            </div>
            <div class="preview-time right">
              <%= recipe.time%>分
            </div>
          </div>
          <div class="preview-item-wrap">
            <div class="preview-user-title">
              <p>作成者</p>
            </div>
            <div class="preview-user right">
              <%= link_to release_account_path(recipe.user.id), class: "preview-name-path" do %>
                <%= recipe.user.name %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="pagination-wrapper">
      <%= paginate @recipes %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<% provide(:title, 'レシピ作成')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <%= render 'shared/in_sidebar'%>
  <div class="content-wrapper">
    <div class="page-title">
      <h1 class="recipe-title-font gray-color">簡単料理を投稿してみよう！</h1>
    </div>
    <div class="recipe-wrapper">
      <div class="recipe-container">
        <%= form_with model: @recipe, local: true do |f| %>
          <div class="recipe-box">
            <div class="recipe-label1">
              <label class="recipe-label gray-color required" for="recipe_name">レシピの名前（２０文字以内）</label>
            </div>
            <div class="recipe-form">
              <%= f.text_field :recipe_name, placeholder: "例：ニラと豚肉のスタミナ丼", class: "recipe-form-ctrl form-space" %>
            </div>
            <div class="main-food-box">
              <p class="main-food-col required">※メインの材料を記入しましよう！<br>（半角英数字不可）</p>
              <%= f.text_field :main_food, placeholder: "例：豚肉", class:"main-food" %>
            </div>
          </div>
          <div class="recipe-col-3">
            <%= f.label :food, id: "food", class: "fa-2x recipe-label gray-color fa-solid fa-camera center" do %>
              <div class="recipe-label3">
                <p>料理の写真</p>
              </div>
              <div class="recipe-form">
                <%= f.file_field :food %>
              </div>
            <% end %>
            <div class="recipe-number-wrapper">
              <div class="recipe-number-wrapper-col">
                <%= f.label :調理時間, class: "recipe-label gray-color recipe-people required"%>
              </div>
              <div class="field-wrapper flex">
                <%= f.number_field :time, min: 1, class: "recipe-form-ctrl2 gray-color" %>
                <div class="font-people">分</div>
              </div>
              <div class="recipe-number-wrapper-col">
                <%= f.label :値段, class: "recipe-label gray-color recipe-price required"%>
              </div>
              <div class="field-wrapper flex">
                <%= f.number_field :price, min: 1, class: "recipe-form-ctrl2 gray-color" %>
                <div class="font-price">円</div>
              </div>
            </div>
          </div>
          <div class="recipe-sentence-box">
            <nav class="recipe-introduction">
              <div class="recipe-label2">
                <label class="recipe-label gray-color" for="recipe_introduction">作り方</label>
              </div>
              <div class="recipe-form">
                <%= f.text_area :recipe_how, placeholder: placeholder_method,rows: 4, class: "recipe-intro-form-ctrl form-space" %>
              </div>
            </nav>
            <nav class="recipe-trick">
              <div class="recipe-label2">
                <%= f.label :材料・分量, class: "recipe-label gray-color" %>
              </div>
              <div class="recipe-form">
                <%= f.text_area :material, placeholder: placeholder_material,rows: 4, class: "recipe-intro-form-ctrl form-space" %>
              </div>
            </nav>
          </div>
          <%= f.hidden_field :user_id, value:@user.id %>
          <% if @user.name == "ゲスト" %>
          <div class="no-edit-guest">
            <p>（注）ゲストユーザーの場合、登録後編集できません。</p>
          </div>
          <% end %>
          <div class="submit center">
            <%= f.submit "登録する", class: "create-recipe-submit" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/release.html.erb
<% provide(:title, '公開レシピの詳細')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <% if user_signed_in? %>
    <%= render 'shared/in_sidebar'%>
  <% else %>
    <%= render 'shared/out_sidebar'%>
  <% end %>
  <div class="content-wrapper">
    <div class="show-recipe-wrapper">
      <div class="recipe-container">
        <%= form_with model: @recipe, local: true do |f| %>
          <div class="show-recipe-col">
            <div class="show-recipe-name">
              <%= @recipe.recipe_name %>
            </div>
            <div class="tag-main-food">
              # <%= @recipe.main_food%>
            </div>
            <div class="recipe-right-box">
              <div class="recipe-right-item m-bottom05">
                <div class="recipe-right-item-label">
                  調理時間
                </div>
                <div>
                  <%= @recipe.time%> 分
                </div>
              </div>
              <div class="recipe-right-item">
                <div class="recipe-right-item-label">
                  費用
                </div>
                <div>
                  <%= @recipe.price%> 円
                </div>
              </div>
            </div>
          </div>
          <div class="show-recipe-col2">
            <% if @recipe.food.present? %>
              <%= image_tag @recipe.food.url, alt: "レシピ写真", class: "show-food" %>
            <% else %>
              <%= f.label :food, id: "no-food", class: "fa-2x recipe-label gray-color fa-solid fa-camera center" do %>
                <div class="recipe-label3">
                  <p>写真が登録されていません</p>
                </div>
              <% end %>
            <% end %>
            <div class="show-recipe-sentence-wrap">
              <div class="show-recipe-label">
                <label class="recipe-label gray-color" for="recipe_introduction">作り方</label>
              </div>
              <div class="show-recipe-form">
                <%= f.text_area :recipe_how, rows: 4, class: "sentence-form form-space", readonly: true %>
              </div>
              <div class="show-recipe-label">
                <%= f.label :材料・分量, class: "recipe-label gray-color" %>
              </div>
              <div class="show-recipe-form">
                <%= f.text_area :material, rows: 4, class: "sentence-form form-space", readonly: true %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="release-favorite">
              <% if user_signed_in? %>
                <% if favorite = @recipe.favorites.find_by(user_id: current_user.id) %>
                  <%= link_to recipe_favorite_path(@recipe.id), method: :delete, remote:true, style: "color: red;" do %>
                    いいねしてくれてありがとう！<i class="fas fa-thumbs-up"></i>
                  <% end %>
                <% else %>
                  <%= link_to recipe_favorite_path(@recipe), method: :post, remote:true, style: "color: #dc954e;" do %>
                    レシピがよかったらいいね！<i class="fas fa-thumbs-up"></i>
                  <% end %>
                <% end %>
                <%= @recipe.favorites.size %>
              <% end %>
            </div>
        <div class="btn-wrap">
          <%= link_to '戻る', recipes_path, class: "return-recipe-list-btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/search.html.erb
<% provide(:title, '検索結果')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <% if user_signed_in? %>
    <%= render 'shared/in_sidebar'%>
  <% else %>
    <%= render 'shared/out_sidebar'%>
  <% end %>
  <div class="preview-page-wrapper">
    <div class="order-title-wrap">
      <h2 class="order-title gray-color center">検索結果：<%= @counts%>件</h2>
      <p class="order-title-comment center"></p>
    </div>
    <div class="search-wrap center">
      <%= form_with(url: search_recipes_path, local: true, method: :get ) do |f| %>
        <%= f.search_field :keyword, class: 'recipe-name-search', placeholder: 'キーワードで検索' %>
        <%= f.submit '検索', class: "submit-search"%>
      <% end %>
    </div>
    <% @search.each do |recipe| %>
      <div class="recipe-preview">
        <% if recipe.food? %>
          <%= link_to release_recipe_path(recipe.id) do %>
            <%= image_tag recipe.food.url, alt: "レシピ写真", class: "food-preview-img" %>
          <% end %>
        <% else %>
          <%= link_to release_recipe_path(recipe.id), class: "preview-name-path" do %>
            <div class="not-food-img-box">
              <div class="not-food-img-posi">
                <div>
                  <i class="not-food-img fa-solid fa-utensils"></i>
                </div>
                <div class="not-found">
                  <p>not-image</p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <div class="recipe-preview-wrapp">
          <div class="preview-name">
            <%= link_to release_recipe_path(recipe.id), class: "preview-name-path" do %>
              <%= recipe.recipe_name %>
            <% end %>
          </div>
          <div class="preview-item-wrap">
            <div class="preview-price-title">
              <p>調理の費用</p>
            </div>
            <div class="preview-price right">
              <%= recipe.price%>円
            </div>
          </div>
          <div class="preview-item-wrap">
            <div class="preview-time-title">
              <p>調理にかかる時間</p>
            </div>
            <div class="preview-time right">
              <%= recipe.time%>分
            </div>
          </div>
          <div class="preview-item-wrap">
            <div class="preview-user-title">
              <p>作成者</p>
            </div>
            <div class="preview-user right">
              <%= link_to release_account_path(recipe.user.id), class: "preview-name-path" do %>
                <%= recipe.user.name %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="pagination-wrapper">
      <%= paginate @search %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<% provide(:title, '個人レシピ詳細')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <%= render 'shared/in_sidebar'%>
  <div class="content-wrapper">
    <div class="show-recipe-wrapper">
      <div class="recipe-container">
        <%= form_with model: @recipe, local: true do |f| %>
          <div class="show-recipe-col">
            <div class="show-recipe-name">
              <%= @recipe.recipe_name %>
            </div>
            <div class="recipe-right-box">
              <div class="recipe-right-item m-bottom05">
                <div>
                  調理時間
                </div>
                <div>
                  <%= @recipe.time%> 分
                </div>
              </div>
              <div class="recipe-right-item">
                <div>
                  費用
                </div>
                <div>
                  <%= @recipe.price%> 円
                </div>
              </div>
            </div>
          </div>
          <div class="show-recipe-col2">
            <% if @recipe.food.present? %>
              <%= image_tag @recipe.food.url, alt: "レシピ写真", class: "show-food" %>
            <% else %>
              <%= f.label :food, id: "no-food", class: "fa-2x recipe-label gray-color fa-solid fa-camera center" do %>
                <div class="recipe-label3">
                  <p>写真が登録されていません</p>
                </div>
              <% end %>
            <% end %>
            <div class="show-recipe-sentence-wrap">
              <div class="show-recipe-label">
                <label class="recipe-label gray-color" for="recipe_introduction">作り方</label>
              </div>
              <div class="show-recipe-form">
                <%= f.text_area :recipe_how, placeholder: placeholder_method,rows: 4, class: "sentence-form form-space", readonly: true %>
              </div>
              <div class="show-recipe-label">
                <%= f.label :材料・分量, class: "recipe-label gray-color" %>
              </div>
              <div class="show-recipe-form">
                <%= f.text_area :material, placeholder: placeholder_material,rows: 4, class: "sentence-form form-space", readonly: true %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="btn-wrap">
          <%= link_to '編集する', edit_recipe_path, class: "return-recipe-list-btn" %>
        </div>
        <div class="show-recipe-btn-wrap">
          <%= link_to "戻る", account_path(@user.id), class:"return-myrecipe-btn"%>
        </div>
      </div>
    </div>
  </div>
</div>