config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get '/', to: 'tops#index'
  get 'about', to: 'tops#about'
  resources :accounts, only: %i[show edit update] do
    collection do
      get 'withdrawal'
    end

    member do
      get 'release'
    end
  end

  resources :recipes, only: %i[index new create show edit update destroy] do
    resource :favorite, only: %i[create destroy]

    member do
      get 'release'
    end

    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-item">
      <p class="footer-title-icon">©2022 ひとり飯</p>
    </div>
  </div>
</footer>

app/views/shared/_hamburger_menu.html.erb
<button type="button" class="menu-btn">
  <i class="fa fa-bars fa-2x" aria-hidden="true"></i>
</button>
<div class="menu">
  <div class="menu__item">
    <%= link_to "/", class: "js-list-item" do %>
      ホーム
    <% end %>
  </div>
  <div class="menu__item">
    <%= link_to about_path, class: "js-list-item" do %>
      コンセプト
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="menu__item">
      <%= link_to "マイページ", account_path(@user), class: "js-list-item" %>
    </div>
    <div class="menu__item">
      <%= link_to  "ログアウト", destroy_user_session_path,class: "js-list-item", data: {confirm: "ログアウトしますか？"}, method: :delete %>
    </div>
  <% else %>
    <div class="menu__item">
      <%= link_to new_user_registration_path, class: "js-list-item" do %>
        新規登録
      <% end %>
    </div>
    <div class="menu__item">
      <%= link_to user_session_path, class: "js-list-item" do %>
        ログイン
      <% end %>
    </div>
  <% end %>
  <div class="menu__item">
    <%= link_to 'レシピ一覧', recipes_path, class: "js-list-item" %>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar">
    <div class="container">
      <div class="header-items">
        <div class="header-left">
          <%= link_to "/", class: "header-logo" do%>
            <h1 class="title-icon">ひとり飯</h1>
          <% end %>
        </div>
        <div class="header-right">
          <% if user_signed_in? %>
            <div class="recipe-create">
              <nav class="nav-header-top-search">
                <%= form_with(url: search_recipes_path, local: true, method: :get ) do |f| %>
                  <%= f.search_field :keyword, class: 'header-search', placeholder: 'キーワードで検索' %>
                <% end %>
              </nav>
              <%= link_to "レシピ作成", new_recipe_path(@user), class: "size recipe-btn"%>
            </div>
            <%= render 'shared/hamburger_menu' %>
          <% else %>
            <div class="recipe-create">
              <nav class="nav-header-top-search">
                <%= form_with(url: search_recipes_path, local: true, method: :get ) do |f| %>
                  <%= f.search_field :keyword, class: 'header-search', placeholder: 'キーワードで検索' %>
                <% end %>
              </nav>
              <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "size recipe-btn", method: :post %>
              <%= render 'shared/hamburger_menu' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>
<script>
document.querySelector('.menu-btn').addEventListener('click', function(){
    document.querySelector('.menu').classList.toggle('is-active');
});
</script>

app/views/shared/_in_sidebar.html.erb
<nav class="nav-side-list">
  <div class="side-wrapper">
    <div class="side-title">
      <%= link_to "/", class: "side-logo" do%>
        <h1 class="title-icon">ひとり飯</h1>
      <% end %>
    </div>
    <nav id="nav-list">
      <div class="side-list">
        <div>
          <ul class="menu-list">
            <li class="memu1">
              <%= link_to "/", class: "list-item" do %>
                <i class="fa-solid fa-house push-right"></i>Home
              <% end %>
            </li>
            <% if current_page?("/")  %>
              <li>
                <%= link_to anchor: "concept-anchor" do %>
                  <div class="flex">
                    <p class="fa-solid fa-book push-right list-item inline"></p><p class="list-item inline">Concept</p>
                  </div>
                <% end %>
              </li>
            <% else %>
            <li>
              <%= link_to about_path, class: "list-item" do %>
                <i class="fa-solid fa-book push-right"></i>Concept
              <% end %>
            </li>
            <% end %>
            <li>
              <button class="btn-menu list-item", id= "menu-btn menu-event", onclick="clickBtn1()">
                <i class="fa-solid fa-user push-right"></i>User
              </button>
              <nav id="nav-none">
                <ul class="user-list user-list-spec">
                  <li><%= link_to "マイページ", account_path(@user), class: "user-list-item" %></li>
                  <li><%= link_to "アカウント編集", edit_user_registration_path, class: "user-list-item" %></li>
                  <li><%= link_to '退会手続き', withdrawal_accounts_path, class: "user-list-item" %></li>
                  <li><%= link_to  "ログアウト", destroy_user_session_path,class: "user-list-item logout-color", data: {confirm: "ログアウトしますか？"}, method: :delete %></li>
                </ul>
              </nav>
            </li>
            <li>
              <button class="btn-menu list-item", id= "menu-btn menu-event", onclick="clickBtn2()">
                <i class="fa-solid fa-utensils push-right"></i>Recipe
              </button>
              <nav id="nav-none2">
                <ul class="user-list user-list-spec-second">
                  <li><%= link_to "新規レシピ一覧", recipes_path, class: "user-list-item" %></li>
                  <li><%= link_to "レシピ作成", new_recipe_path, class: "user-list-item" %></li>
                </ul>
              </nav>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</nav>
<script>
  document.getElementById("nav-none").style.display = "none";
  function clickBtn1() {
    const p1 = document.getElementById("nav-none");
    if(p1.style.display == "block") {
      p1.style.display = "none";
    }else{
      p1.style.display = "block"
      document.addEventListener('click', (e) => {
        if(!e.target.closest('.menu-list')) {
          p1.style.display = "none";
        }
      })
    }
  }
  document.getElementById("nav-none2").style.display = "none";
  function clickBtn2() {
    const p1 = document.getElementById("nav-none2");
    if(p1.style.display == "block") {
      p1.style.display = "none";
    }else{
      p1.style.display = "block"
      document.addEventListener('click', (e) => {
        if(!e.target.closest('.menu-list')) {
          p1.style.display = "none";
        }
      })
    }
  }
</script>

app/views/shared/_left_sidebar_html.erb
<div class="side-nav">
  <nav id="menu-list">
    <div class="header">
      <div>
        <ul class="nav-list">
          <li>
            <%= link_to "/", class: "list-item" do %>
              Home<i class="fa-solid fa-house"></i>
            <% end %>
          </li>
          <li>
            <p class="list-item">About</p>
          </li>
          <li>
            <p class="list-item">Login</p>
          </li>
          <li>
            <p class="list-item">SignUp</p>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_out_sidebar.html.erb
<nav class="nav-side-list">
  <div class="side-wrapper">
    <div class="side-title">
      <%= link_to "/", class: "side-logo" do%>
        <h1 class="title-icon">ひとり飯</h1>
      <% end %>
    </div>
    <nav id="nav-list">
      <div class="side-list">
        <div>
          <ul class="menu-list">
            <li class="menu1">
              <%= link_to "/", class: "list-item" do %>
                <i class="fa-solid fa-house push-right"></i>Home
              <% end %>
            </li>
            <% if current_page?("/")  %>
              <li>
                <%= link_to anchor: "concept-anchor" do %>
                  <div class="flex">
                    <p class="fa-solid fa-book push-right list-item inline"></p><p class="list-item inline">Concept</p>
                  </div>
                <% end %>
              </li>
            <% else %>
            <li>
              <%= link_to about_path, class: "list-item" do %>
                <i class="fa-solid fa-book push-right"></i>Concept
              <% end %>
            </li>
            <% end %>
            <% unless current_page?(user_session_path)%>
              <li>
                <%= link_to user_session_path, class: "list-item" do %>
                  <i class="fa-solid fa-right-to-bracket push-right"></i>Login
                <% end %>
              </li>
            <% end %>
            <% unless current_page?(new_user_registration_path)%>
              <li>
                <%= link_to new_user_registration_path, class: "list-item" do %>
                  <i class="fa-solid fa-pen push-right"></i>SignUp
                <% end %>
              </li>
            <% end %>
            <li>
              <%= link_to recipes_path, class: "list-item" do %>
                <i class="fa-solid fa-utensils push-right"></i>Recipe
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</nav>
<script>
  document.getElementById("nav-none").style.display = "none";
  function clickBtn1() {
    const p1 = document.getElementById("nav-none");
    if(p1.style.display == "block") {
      p1.style.display = "none";
    }else{
      p1.style.display = "block"
      document.addEventListener('click', (e) => {
        if(!e.target.closest('.menu-list')) {
          p1.style.display = "none";
        }
      })
    }
  }

  document.getElementById("nav-none2").style.display = "none";
  function clickBtn2() {
    const p1 = document.getElementById("nav-none2");
    if(p1.style.display == "block") {
      p1.style.display = "none";
    }else{
      p1.style.display = "block"
      document.addEventListener('click', (e) => {
        if(!e.target.closest('.menu-list')) {
          p1.style.display = "none";
        }
      })
    }
  }
</script>