config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get '/', to: 'tops#index'
  get 'about', to: 'tops#about'
  resources :accounts, only: %i[show edit update] do
    collection do
      get 'withdrawal'
    end

    member do
      get 'release'
    end
  end

  resources :recipes, only: %i[index new create show edit update destroy] do
    resource :favorite, only: %i[create destroy]

    member do
      get 'release'
    end

    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!, except: [:release]
  def show
    @user = current_user
    @recipes = current_user.recipes.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    if @user.name != "ゲスト" && @user.update(account_update)
      redirect_to account_path(@user)
    else
      redirect_to "/", flash: { info: "ゲストユーザーは編集することができません。" }
    end
  end

  def withdrawal
    @user = current_user
  end

  def release
    @user = current_user
    @release_user = User.find(params[:id])
    @recipes = @release_user.recipes.order(created_at: :desc)
  end

  private

  def account_update
    params.require(:user).permit(:name, :introduction, :recommended_dishes, :avatar)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<% provide(:title, 'プロフィール編集')%>
<div class="main">
  <%= render 'shared/in_sidebar'%>
  <div class="content-wrapper">
    <div class="page-title">
      <h1 class="signup-icon title-font">マイページ編集</h1>
    </div>
    <div class="content-user">
      <div class="container-content user-form auto-center">
        <div class="content-document-inner">
          <%= form_with model: @user, url: account_path(@user), local: true do |f| %>
            <div class="field">
              <div class="user-content">
                <div class="data-user">
                  <div class="user-icon-wrap">
                    <% if @user.avatar? %>
                      <%= image_tag @user.avatar.url, alt: "プロフィール写真", class: "user-icon-img"%>
                    <% else %>
                      <div class="user-icon">
                        <i class="fa-solid fa-user-gear show-user-icon gray-color"></i>
                      </div>
                    <% end %>
                  </div>
                  <div class="user-content">
                    <div class="user-name">
                      <%= f.file_field :avatar%>
                    </div>
                  </div>
                </div>
              </div>
              <div class="user-content">
                <label class="user-label" for="name">ニックネーム</label>
                <div class="user-content-item">
                  <%= f.text_field :name, class: "form-control form-space" %>
                </div>
              </div>
              <div class="user-content">
                <label class="user-label" for="introduction">自己紹介</label>
                <div class="user-content-item">
                  <%= f.text_area :introduction, rows: 4, class: "form-control form-space"%>
                </div>
              </div>
            </div>
            <div class="actions">
              <%= f.submit "更新", class: "form-submit base-btn" %>
            </div>
            <div class="actions">
              <%= link_to "戻る", account_path(@user), class: "return-link base-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/release.html.erb
<% provide(:title, '公開プロフィール')%>
<div class="main">
  <% if user_signed_in? %>
    <%= render 'shared/in_sidebar'%>
  <% else %>
    <%= render 'shared/out_sidebar'%>
  <% end %>
  <div class="content-wrapper">
    <div class="page-title">
      <h1 class="signup-icon title-font"><%= @release_user.name%>さんのプロフィール</h1>
    </div>
    <div class="mypage-container-wrap">
      <div class="mypage-content">
        <div class="data-user">
          <div class="user-icon-wrap">
            <% if @release_user.avatar? %>
              <%= image_tag @release_user.avatar.url, alt: "プロフィール写真", class: "user-icon-img" %>
            <% else %>
              <div class="user-icon">
                <i class="fa-solid fa-user-gear show-user-icon gray-color"></i>
              </div>
            <% end %>
          </div>
          <div class="user-content">
            <div class="user-name">
              <%= @release_user.name%>
            </div>
          </div>
        </div>
        <div class="user-introduction-wrap">
          <div class="introduction-label">自己紹介</div>
          <% if @release_user.introduction? %>
            <div class="release-user-introduction">
              <%= safe_join(@release_user.introduction.split("\n"),tag(:br))%>
            </div>
          <% else %>
            <div class="no-introduction">
              登録されていません。
            </div>
          <% end %>
        </div>
        <% unless @release_user.name == "ゲスト" %>
          <div class="myrecipe-list-wrap">
            <div class="myrecipe-label">公開しているレシピ
            </div>
            <div class="myrecipe-name-wrap">
              <% @recipes.each do |recipe| %>
                <div>
                  <%= link_to release_recipe_path(recipe.id), class: "myrecipe-name flex" do %>
                    <p>・</p><%= recipe.recipe_name%>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="edit-mypage-btn-wrap">
          <%= link_to '一覧ページへ', recipes_path, class: "return-recipe-list-btn" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<% provide(:title, 'マイページ')%>
<p class="flash" ><%= flash[:info]%></p>
<p class="alert"><%= alert%></p>
<div class="main">
  <%= render 'shared/in_sidebar'%>
  <div class="content-wrapper">
    <div class="page-title">
      <h1 class="signup-icon title-font">マイページ</h1>
    </div>
    <div class="mypage-container-wrap">
      <div class="mypage-content">
        <div class="data-user">
          <div class="user-icon-wrap">
            <% if @user.avatar? %>
              <%= image_tag @user.avatar.url, alt: "プロフィール写真", class: "user-icon-img" %>
            <% else %>
              <div class="user-icon">
                <i class="fa-solid fa-user-gear show-user-icon gray-color"></i>
              </div>
            <% end %>
          </div>
          <div class="user-content">
            <div class="user-name">
              <%= @user.name%>
            </div>
          </div>
        </div>
        <div class="user-introduction-wrap">
          <div class="introduction-label">自己紹介</div>
          <div class="user-content-item">
            <%= form_with model: @user, url: account_path(@user), local: true do |f| %>
              <%= f.text_area :introduction, rows: 2, class: "no-edit-form", readonly: true %>
            <% end %>
          </div>
        </div>
        <div class="myrecipe-list-wrap">
          <div class="myrecipe-label">マイレシピ</div>
          <div class="myrecipe-name-wrap">
            <% if @user.recipes.present? %>
              <% @recipes.each do |recipe| %>
                <div>
                  <%= link_to recipe_path(recipe.id), class: "myrecipe-name" do %>
                    <%= recipe.recipe_name%>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <div class="no-myrecipe-name-wrap">
                <p>レシピはまだ作成されていません</p>
              </div>
            <% end %>
          </div>
        </div>
        <div class="edit-mypage-btn-wrap">
          <%= link_to "編集する", edit_account_path, class: "edit-mypage-btn" %>
        </div>
      </div>
    </div>
    <div class="mypage-list">
      <ul>
        <li><%= link_to "マイページ編集", edit_account_path, class: "mypage-list-font" %></li>
        <li><%= link_to '退会手続き', withdrawal_accounts_path, class: "mypage-list-font" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/accounts/withdrawal.erb
<% provide(:title, '退会手続き')%>
<p class="flash" ><%= flash[:info]%></p>
<div class="main">
  <%= render 'shared/in_sidebar'%>
  <div class="content-wrapper">
  <div class="page-title">
    <h1 class="title-font">退会お手続き</h1>
  </div>
    <div class="content-about merge-4">
      <div class="container-content">
        <div class="content-document-inner", id="about">
          <p>退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>本当に退会してよろしいですか？
          </p>
          <div class="withdrawal-btn-wrapper">
            <%= link_to '退会する', user_registration_path, class: "withdrawal-btn", data: {confirm: "退会しますか？"}, method: :delete %>
          </div>
          <div class="return-mypage-btn-wrapper">
            <%= link_to '戻る', account_path(@user.id), class: "withdrawal-return-link base-withdrawal-btn"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>